// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zoMAhQ0Ig_FgUoTo8Fx6U0nogmp5H5I',
    appId: '1:452582285981:web:45eabcc7cfda93684fea74',
    messagingSenderId: '452582285981',
    projectId: 'utilitarian-bee-kv9wh',
    authDomain: 'utilitarian-bee-kv9wh.firebaseapp.com',
    storageBucket: 'utilitarian-bee-kv9wh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2zoMAhQ0Ig_FgUoTo8Fx6U0nogmp5H5I',
    appId: '1:452582285981:android:45eabcc7cfda93684fea74',
    messagingSenderId: '452582285981',
    projectId: 'utilitarian-bee-kv9wh',
    storageBucket: 'utilitarian-bee-kv9wh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zoMAhQ0Ig_FgUoTo8Fx6U0nogmp5H5I',
    appId: '1:452582285981:ios:45eabcc7cfda93684fea74',
    messagingSenderId: '452582285981',
    projectId: 'utilitarian-bee-kv9wh',
    storageBucket: 'utilitarian-bee-kv9wh.firebasestorage.app',
    iosBundleId: 'pk.edu.comsats.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2zoMAhQ0Ig_FgUoTo8Fx6U0nogmp5H5I',
    appId: '1:452582285981:ios:45eabcc7cfda93684fea74',
    messagingSenderId: '452582285981',
    projectId: 'utilitarian-bee-kv9wh',
    storageBucket: 'utilitarian-bee-kv9wh.firebasestorage.app',
    iosBundleId: 'pk.edu.comsats.portal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2zoMAhQ0Ig_FgUoTo8Fx6U0nogmp5H5I',
    appId: '1:452582285981:web:45eabcc7cfda93684fea74',
    messagingSenderId: '452582285981',
    projectId: 'utilitarian-bee-kv9wh',
    authDomain: 'utilitarian-bee-kv9wh.firebaseapp.com',
    storageBucket: 'utilitarian-bee-kv9wh.firebasestorage.app',
  );
}
