import { Course, Instructor, NotificationItem, Section, SemesterHistoryItem, Student } from './types';

export const initialStudent: Student = {
  id: 'std_042',
  name: 'Hassan Raza',
  registrationNumber: 'SP24-BCE-042',
  email: 'sp24-bce-042@isb.comsats.edu.pk',
  phoneNumber: '+92 312 8765432',
  program: 'BS Computer Engineering (BCE)',
  campus: 'Islamabad Campus',
  batch: 'Spring 2024',
  semester: 3,
  cgpa: 3.42,
  completedCreditHours: 64,
  academicStanding: 'Good Standing',
};

export const completedCourseCodes = new Set(['CSC101', 'MTH101', 'HUM100', 'PHY120', 'EEE111', 'MTH105', 'CSC102', 'ISL101']);

export const mockInstructors: Instructor[] = [
  {
    id: 'inst_1',
    name: 'Dr. Ahmed Khan',
    designation: 'Associate Professor',
    department: 'Computer Science',
    coursesTaught: ['CSC241 Object Oriented Programming', 'CSC312 Design & Analysis of Algorithms'],
    office: 'CS Building, Room 304',
    email: 'ahmed.khan@comsats.edu.pk',
    phone: '+92 51 9247000 Ext 204',
  },
  {
    id: 'inst_2',
    name: 'Dr. Ali Raza',
    designation: 'Assistant Professor',
    department: 'Computer Engineering',
    coursesTaught: ['CPE241 Digital Logic Design', 'CPE321 Microprocessor Systems'],
    office: 'EE Building, Room 212',
    email: 'ali.raza@comsats.edu.pk',
    phone: '+92 51 9247000 Ext 212',
  },
  {
    id: 'inst_3',
    name: 'Dr. Fatima Zahra',
    designation: 'Professor & HOD',
    department: 'Computer Science',
    coursesTaught: ['CSC291 Software Engineering', 'CSC490 Final Year Project'],
    office: 'Faculty Block B, Room 101',
    email: 'fatima.zahra@comsats.edu.pk',
    phone: '+92 51 9247000 Ext 101',
  },
  {
    id: 'inst_4',
    name: 'Dr. Sarah Tariq',
    designation: 'Assistant Professor',
    department: 'Mathematics',
    coursesTaught: ['MTH242 Differential Equations', 'MTH101 Calculus'],
    office: 'Math Block, Room 115',
    email: 'sarah.tariq@comsats.edu.pk',
    phone: '+92 51 9247000 Ext 115',
  },
  {
    id: 'inst_5',
    name: 'Engr. Bilal Tariq',
    designation: 'Lecturer',
    department: 'Computer Engineering',
    coursesTaught: ['CPE241 Digital Logic Design Lab', 'CSC241 OOP Lab'],
    office: 'Hardware Lab 3',
    email: 'bilal.tariq@comsats.edu.pk',
    phone: '+92 51 9247000 Ext 230',
  },
];

export const mockCourses: Course[] = [
  {
    code: 'CSC241',
    title: 'Object Oriented Programming',
    creditHours: 4,
    department: 'Computer Science',
    description: 'Advanced programming paradigms, object-oriented concepts: classes, inheritance, polymorphism, templates, exception handling, and GUI development.',
    prerequisites: ['CSC101'],
    corequisites: [],
    courseType: 'Core',
    recommendedSemester: 3,
  },
  {
    code: 'CPE241',
    title: 'Digital Logic Design',
    creditHours: 4,
    department: 'Computer Engineering',
    description: 'Number systems, Boolean algebra, logic gates, combinational and sequential circuit design, Karnaugh maps, counters, registers, and HDL simulation.',
    prerequisites: ['EEE111'],
    corequisites: [],
    courseType: 'Core',
    recommendedSemester: 3,
  },
  {
    code: 'CSC291',
    title: 'Software Engineering',
    creditHours: 3,
    department: 'Computer Science',
    description: 'Systematic approach to development, maintenance, and testing of complex software systems. Agile methodologies, UML modeling, requirements engineering, and CI/CD pipelines.',
    prerequisites: ['CSC101'],
    corequisites: [],
    courseType: 'Core',
    recommendedSemester: 3,
  },
  {
    code: 'MTH242',
    title: 'Differential Equations',
    creditHours: 3,
    department: 'Mathematics',
    description: 'First order and second order ordinary differential equations, Laplace transforms, Fourier series, and applications in engineering systems.',
    prerequisites: ['MTH101'],
    corequisites: [],
    courseType: 'Core',
    recommendedSemester: 3,
  },
  {
    code: 'CSC312',
    title: 'Algorithms Analysis & Design',
    creditHours: 3,
    department: 'Computer Science',
    description: 'Asymptotic notation, divide and conquer, dynamic programming, greedy algorithms, graph traversals, shortest paths, and NP-completeness.',
    prerequisites: ['CSC241'], // Missing prerequisite (CSC241 currently taking)
    corequisites: [],
    courseType: 'Core',
    recommendedSemester: 4,
  },
  {
    code: 'HUM102',
    title: 'Report Writing Skills',
    creditHours: 3,
    department: 'Humanities',
    description: 'Techniques of formal technical writing, research reports, executive summaries, presentations, and professional ethics.',
    prerequisites: ['HUM100'],
    corequisites: [],
    courseType: 'University Requirement',
    recommendedSemester: 3,
  },
  {
    code: 'CPE321',
    title: 'Microprocessor Systems',
    creditHours: 4,
    department: 'Computer Engineering',
    description: 'Architecture and assembly language programming of x86/ARM microprocessors, bus interfacing, interrupts, DMA, and memory hierarchies.',
    prerequisites: ['CPE241'],
    corequisites: [],
    courseType: 'Core',
    recommendedSemester: 4,
  },
  {
    code: 'MTH262',
    title: 'Statistics and Probability',
    creditHours: 3,
    department: 'Mathematics',
    description: 'Random variables, discrete and continuous probability distributions, regression, correlation, hypothesis testing, and statistical estimation.',
    prerequisites: ['MTH101'],
    corequisites: [],
    courseType: 'Core',
    recommendedSemester: 3,
  },
  {
    code: 'CSC339',
    title: 'Data Communication & Networking',
    creditHours: 4,
    department: 'Computer Science',
    description: 'OSI and TCP/IP protocol architectures, packet routing, transport layer protocols, addressing, wireless standards, and network security.',
    prerequisites: ['CSC101'],
    corequisites: [],
    courseType: 'Elective',
    recommendedSemester: 4,
  },
  {
    code: 'ENV100',
    title: 'Environmental Sciences',
    creditHours: 3,
    department: 'Humanities',
    description: 'Ecology, sustainable energy, pollution control, resource management, and environmental laws.',
    prerequisites: [],
    corequisites: [],
    courseType: 'University Requirement',
    recommendedSemester: 3,
  },
];

export const mockSections: Section[] = [
  // CSC241
  {
    id: 'sec_csc241_a',
    courseCode: 'CSC241',
    sectionName: 'Section A',
    instructor: 'Dr. Ahmed Khan',
    instructorId: 'inst_1',
    days: ['Monday', 'Wednesday'],
    startTime: '09:00 AM',
    endTime: '10:30 AM',
    room: 'C-Block 204',
    totalSeats: 40,
    availableSeats: 8,
  },
  {
    id: 'sec_csc241_b',
    courseCode: 'CSC241',
    sectionName: 'Section B',
    instructor: 'Dr. Ahmed Khan',
    instructorId: 'inst_1',
    days: ['Tuesday', 'Thursday'],
    startTime: '01:00 PM',
    endTime: '02:30 PM',
    room: 'Lab 4',
    totalSeats: 40,
    availableSeats: 0, // Full
  },
  {
    id: 'sec_csc241_c',
    courseCode: 'CSC241',
    sectionName: 'Section C',
    instructor: 'Engr. Bilal Tariq',
    instructorId: 'inst_5',
    days: ['Tuesday', 'Thursday'],
    startTime: '10:30 AM',
    endTime: '12:00 PM',
    room: 'C-Block 201',
    totalSeats: 35,
    availableSeats: 14,
  },

  // CPE241
  {
    id: 'sec_cpe241_a',
    courseCode: 'CPE241',
    sectionName: 'Section A',
    instructor: 'Dr. Ali Raza',
    instructorId: 'inst_2',
    days: ['Monday', 'Wednesday'],
    startTime: '11:00 AM',
    endTime: '12:30 PM',
    room: 'Hardware Lab 3',
    totalSeats: 35,
    availableSeats: 6,
  },
  {
    id: 'sec_cpe241_b',
    courseCode: 'CPE241',
    sectionName: 'Section B',
    instructor: 'Engr. Bilal Tariq',
    instructorId: 'inst_5',
    days: ['Monday', 'Wednesday'],
    startTime: '09:30 AM',
    endTime: '11:00 AM', // Conflict with CSC241 Sec A
    room: 'EE-Block 102',
    totalSeats: 35,
    availableSeats: 12,
  },

  // CSC291
  {
    id: 'sec_csc291_a',
    courseCode: 'CSC291',
    sectionName: 'Section A',
    instructor: 'Dr. Fatima Zahra',
    instructorId: 'inst_3',
    days: ['Tuesday', 'Thursday'],
    startTime: '09:00 AM',
    endTime: '10:30 AM',
    room: 'C-Block 305',
    totalSeats: 45,
    availableSeats: 15,
  },
  {
    id: 'sec_csc291_b',
    courseCode: 'CSC291',
    sectionName: 'Section B',
    instructor: 'Dr. Fatima Zahra',
    instructorId: 'inst_3',
    days: ['Friday'],
    startTime: '09:00 AM',
    endTime: '12:00 PM',
    room: 'CS Seminar Hall',
    totalSeats: 45,
    availableSeats: 20,
  },

  // MTH242
  {
    id: 'sec_mth242_a',
    courseCode: 'MTH242',
    sectionName: 'Section A',
    instructor: 'Dr. Sarah Tariq',
    instructorId: 'inst_4',
    days: ['Monday', 'Wednesday'],
    startTime: '01:30 PM',
    endTime: '03:00 PM',
    room: 'Math Block 112',
    totalSeats: 50,
    availableSeats: 11,
  },

  // HUM102
  {
    id: 'sec_hum102_a',
    courseCode: 'HUM102',
    sectionName: 'Section A',
    instructor: 'Dr. Sarah Tariq',
    instructorId: 'inst_4',
    days: ['Tuesday', 'Thursday'],
    startTime: '03:00 PM',
    endTime: '04:30 PM',
    room: 'Hum Block 201',
    totalSeats: 40,
    availableSeats: 19,
  },

  // MTH262
  {
    id: 'sec_mth262_a',
    courseCode: 'MTH262',
    sectionName: 'Section A',
    instructor: 'Dr. Sarah Tariq',
    instructorId: 'inst_4',
    days: ['Friday'],
    startTime: '02:30 PM',
    endTime: '05:30 PM',
    room: 'Math Block 110',
    totalSeats: 45,
    availableSeats: 18,
  },

  // CSC312
  {
    id: 'sec_csc312_a',
    courseCode: 'CSC312',
    sectionName: 'Section A',
    instructor: 'Dr. Ahmed Khan',
    instructorId: 'inst_1',
    days: ['Monday', 'Wednesday'],
    startTime: '03:00 PM',
    endTime: '04:30 PM',
    room: 'C-Block 204',
    totalSeats: 40,
    availableSeats: 15,
  },
];

export const initialRegistrations = [
  {
    id: 'reg_1',
    studentId: 'std_042',
    courseCode: 'CSC241',
    sectionId: 'sec_csc241_a',
    semester: 'Fall 2026',
    status: 'Registered' as const,
    registrationDate: '2026-09-25',
  },
  {
    id: 'reg_2',
    studentId: 'std_042',
    courseCode: 'CPE241',
    sectionId: 'sec_cpe241_a',
    semester: 'Fall 2026',
    status: 'Registered' as const,
    registrationDate: '2026-09-25',
  },
  {
    id: 'reg_3',
    studentId: 'std_042',
    courseCode: 'CSC291',
    sectionId: 'sec_csc291_a',
    semester: 'Fall 2026',
    status: 'Registered' as const,
    registrationDate: '2026-09-26',
  },
  {
    id: 'reg_4',
    studentId: 'std_042',
    courseCode: 'MTH242',
    sectionId: 'sec_mth242_a',
    semester: 'Fall 2026',
    status: 'Registered' as const,
    registrationDate: '2026-09-26',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Course Registration is Open',
    message: 'Your Fall 2026 course registration period has started. Please select sections carefully.',
    time: '2 hours ago',
    isRead: false,
  },
  {
    id: 'notif_2',
    title: 'Registration Deadline',
    message: 'Course registration closes on September 30, 2026. Late registrations will not be entertained.',
    time: '1 day ago',
    isRead: false,
  },
  {
    id: 'notif_3',
    title: 'Section Availability',
    message: 'A seat has become available in CSC241 Section B.',
    time: '2 days ago',
    isRead: true,
  },
];

export const mockSemesterHistory: SemesterHistoryItem[] = [
  {
    semester: 'Spring 2024',
    gpa: 3.52,
    creditHours: 16,
    courses: [
      { code: 'CSC101', title: 'Programming Fundamentals', ch: 4, grade: 'A' },
      { code: 'MTH101', title: 'Calculus & Analytical Geometry', ch: 3, grade: 'A-' },
      { code: 'HUM100', title: 'English Comprehension', ch: 3, grade: 'B+' },
      { code: 'PHY120', title: 'Applied Physics for Engineers', ch: 4, grade: 'B' },
      { code: 'ISL101', title: 'Islamic Studies', ch: 2, grade: 'A' },
    ],
  },
  {
    semester: 'Fall 2024',
    gpa: 3.32,
    creditHours: 16,
    courses: [
      { code: 'EEE111', title: 'Electric Circuit Analysis', ch: 4, grade: 'A-' },
      { code: 'MTH105', title: 'Multivariable Calculus', ch: 3, grade: 'B+' },
      { code: 'CSC102', title: 'Discrete Structures', ch: 3, grade: 'A' },
      { code: 'HUM102', title: 'Report Writing Skills', ch: 3, grade: 'B' },
      { code: 'ENV100', title: 'Environmental Sciences', ch: 3, grade: 'B+' },
    ],
  },
  {
    semester: 'Spring 2025',
    gpa: 3.45,
    creditHours: 17,
    courses: [
      { code: 'CSC211', title: 'Data Structures', ch: 4, grade: 'B+' },
      { code: 'CPE201', title: 'Basic Electronics', ch: 4, grade: 'A-' },
      { code: 'MTH241', title: 'Linear Algebra', ch: 3, grade: 'A' },
      { code: 'HUM110', title: 'Pakistan Studies', ch: 3, grade: 'A' },
      { code: 'CSC205', title: 'Computer Architecture', ch: 3, grade: 'B' },
    ],
  },
];

export const mockCourseReviews = [
  {
    id: 'rev_1',
    studentId: 'std_099',
    courseCode: 'CSC241',
    courseName: 'Object Oriented Programming',
    instructorId: 'inst_1',
    instructorName: 'Dr. Ahmed Khan',
    semesterId: 'Fall 2025',
    difficulty: 4,
    workload: 4,
    teachingRating: 5,
    organizationRating: 5,
    communicationRating: 4,
    supportRating: 5,
    comment: 'Great course! Make sure to practice pointer concepts and polymorphism early. Dr. Ahmed Khan explains object modeling very clearly with real-world design patterns.',
    anonymous: true,
    status: 'published' as const,
    createdAt: '2025-12-15T10:30:00Z',
  },
  {
    id: 'rev_2',
    studentId: 'std_088',
    courseCode: 'CSC241',
    courseName: 'Object Oriented Programming',
    instructorId: 'inst_1',
    instructorName: 'Dr. Ahmed Khan',
    semesterId: 'Spring 2025',
    difficulty: 3,
    workload: 4,
    teachingRating: 4,
    organizationRating: 4,
    communicationRating: 4,
    supportRating: 4,
    comment: 'Heavy semester project requirement in C++/Qt. Start milestone 1 as soon as groups are formed to avoid late-night debugging in lab.',
    anonymous: true,
    status: 'published' as const,
    createdAt: '2025-05-20T14:15:00Z',
  },
  {
    id: 'rev_3',
    studentId: 'std_077',
    courseCode: 'CPE241',
    courseName: 'Digital Logic Design',
    instructorId: 'inst_2',
    instructorName: 'Dr. Ali Raza',
    semesterId: 'Fall 2025',
    difficulty: 3,
    workload: 3,
    teachingRating: 4,
    organizationRating: 4,
    communicationRating: 5,
    supportRating: 4,
    comment: 'Karnaugh maps and state machines are very intuitive once you do the lab exercises on FPGA boards. Dr. Ali is very supportive during office hours.',
    anonymous: true,
    status: 'published' as const,
    createdAt: '2025-11-28T09:00:00Z',
  },
  {
    id: 'rev_4',
    studentId: 'std_066',
    courseCode: 'CSC291',
    courseName: 'Software Engineering',
    instructorId: 'inst_3',
    instructorName: 'Dr. Fatima Zahra',
    semesterId: 'Spring 2025',
    difficulty: 2,
    workload: 3,
    teachingRating: 5,
    organizationRating: 5,
    communicationRating: 5,
    supportRating: 5,
    comment: 'Focuses heavily on Agile sprints, UML diagrams, and software requirements specification (SRS). Very practical for industry preparation.',
    anonymous: true,
    status: 'published' as const,
    createdAt: '2025-06-02T11:45:00Z',
  },
];

